### ISSUE TITLE
Exposed Firebase API Key

### ISSUE THREAD

**Issue by alicalimli** [alicalimli/Chately#4]

**Comment by creative-tutorials** [comment]
Is this resolved now or would you like me to work on it

**Comment by alicalimli** [comment]
Yes bro so far I've been able to fix this issue, thanks a lot :)
https://github.com/alicalimli/ac-messenger/commit/b4c4d0378bffba994c44f982041324c0e773dc2c

**Comment by creative-tutorials** [comment]
> Yes bro so far I've been able to fix this issue, thanks a lot :) [b4c4d03](https://github.com/alicalimli/ac-messenger/commit/b4c4d0378bffba994c44f982041324c0e773dc2c)

You're Welcome Bro
